import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../styles/globals.css";
import { ThemeProvider } from "next-themes";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "devjeung",
//   description: "Generated by devjeung",
// };
export const metadata: Metadata = {
  title: {
    template: `%s | DevJeung`,
    default: "DevJeung",
  },
  // title: `${APP_NAME}`,
  description: "Generated by devjeung",
  metadataBase: new URL("www.devjeung.com"),
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      {/* <body */}
      {/*   className={`${geistSans.variable} ${geistMono.variable} antialiased`} */}
      {/* > */}
      <body className={`${inter.className} antialiased`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem={true}
          disableTransitionOnChange
        >
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
